// jobs.js

export const jobs = [
  {
    id: 1,
    title: "Content Creator — Apprelab",
    type: "Full-time / Part-time",
    location: "Remote",
    shortDescription: "Craft engaging content to grow Apprelab's platform and community.",
    description: `Apprelab is building Africa's first Learn → Work → Earn ecosystem.
You'll create compelling content for social media, blogs, email, and platform communications that resonates with learners, mentors, and SMEs.
Your work will build brand awareness, attract new users, and engage the community.`,
    responsibilities: [
      "Create content for social media (TikTok, Instagram, X, LinkedIn, YouTube).",
      "Write blogs, newsletters, and copy for the platform and campaigns.",
      "Collaborate with marketing, design, and product teams for content alignment.",
      "Develop creative campaigns that drive user acquisition and engagement.",
      "Repurpose content into multiple formats: videos, graphics, reels, carousel posts, threads.",
      "Monitor performance and adjust content strategies based on analytics.",
    ],
    requirements: [
      "Proven experience as a content creator, copywriter, or social media specialist.",
      "Strong writing and storytelling skills.",
      "Familiarity with social media trends, short-form video, and community engagement.",
      "Basic skills in Canva, Photoshop, CapCut, or video editing tools.",
      "Ability to create content that educates, entertains, and converts.",
    ],
    niceToHave: [
      "Experience in EdTech, SaaS, or startup content creation.",
      "Knowledge of SEO and email marketing.",
      "Video production or animation experience.",
    ],
    offer: [
      "A creative role with high impact in shaping Africa's first Learn → Work → Earn platform.",
      "Flexibility and autonomy in content creation.",
      "Competitive compensation + growth opportunities.",
      "Work in a collaborative, young, and mission-driven environment.",
    ],
    applicationLink: "https://docs.google.com/document/d/1v2Zx7pepjtNzC3skX3xbTyRdqqiFBV7O5UBZpls04F4/edit?usp=drivesdk",
  },
  {
    id: 2,
    title: "UI/UX Designer — Apprelab",
    type: "Full-time",
    location: "Remote/Hybrid",
    shortDescription: "Design beautiful, intuitive, and user-centered experiences across web and mobile.",
    description: `Apprelab is Africa's first Learn → Work → Earn ecosystem. We're creating a platform that allows learners to gain practical experience, mentors to monetize their knowledge, and SMEs to access affordable digital solutions.
You will own the design experience for Apprelab's platform. From wireframes to final prototypes, you'll translate complex workflows into seamless experiences that delight learners, mentors, and SMEs.`,
    responsibilities: [
      "Design and iterate web and mobile user interfaces.",
      "Create wireframes, prototypes, mockups, and design systems.",
      "Collaborate with product, engineering, and marketing teams.",
      "Conduct user research and usability testing to validate designs.",
      "Ensure consistent brand and UX standards across all touchpoints.",
      "Turn insights from analytics and user feedback into actionable design improvements.",
    ],
    requirements: [
      "2+ years experience in UI/UX design for web and mobile apps.",
      "Strong portfolio demonstrating user-centered design solutions.",
      "Proficiency in Figma, Sketch, Adobe XD, or similar tools.",
      "Understanding of interaction design, information architecture, and usability principles.",
      "Ability to work independently in a fast-paced startup environment.",
    ],
    niceToHave: [
      "Experience designing EdTech or SaaS platforms.",
      "Knowledge of motion design or basic front-end development.",
      "Familiarity with analytics tools like Mixpanel, Hotjar, or Google Analytics.",
    ],
    offer: [
      "High ownership in shaping Africa's first Learn → Work → Earn platform.",
      "Competitive salary + growth opportunities.",
      "Flexible working environment.",
      "Collaborate with a young, dynamic, and mission-driven team.",
    ],
    applicationLink: "https://docs.google.com/document/d/1yLc4a_MMq337lZM2I7dkWF-GgvcjnPa6yeRmWapd4hY/edit?usp=drivesdk",
  },
  {
    id: 3,
    title: "Software Engineer — Apprelab (EdTech)",
    type: "Full-time",
    location: "Remote/Hybrid",
    shortDescription: "Build and improve Apprelab's core platform, frontend & backend, and integrations.",
    description: `Apprelab is building the future of digital learning in Africa. We combine smart tech and creative content to make learning fun, effective, and accessible to millions.
With our MVP launched and new features rolling out, we're assembling a world-class engineering team to help us scale.
The Software Engineer will work on building and improving Apprelab's core platform—frontend, backend, integrations, APIs, and performance.
You will collaborate closely with product, design, and growth teams to ship features quickly and efficiently while maintaining high engineering standards.`,
    responsibilities: [
      "Develop new features and improve existing ones across the Apprelab platform.",
      "Write clean, maintainable, and scalable code.",
      "Contribute to UI/UX development, user flows, and product experience.",
      "Build responsive interfaces for mobile and web.",
      "Build and optimize backend services, APIs, and microservices.",
      "Integrate third-party services, payment systems, authentication systems, and analytics tools.",
      "Improve app performance, speed, and reliability.",
      "Conduct code reviews, write tests, and maintain technical documentation.",
      "Debug issues and provide quick fixes to maintain system stability.",
      "Ensure security best practices in code and data handling.",
      "Work with Product Managers, UI/UX Designers, Growth, and Content teams.",
      "Participate in sprint planning, product roadmap discussions, and cross-functional alignment.",
      "Contribute ideas to improve the platform based on user feedback and data insights.",
    ],
    requirements: [
      "Strong proficiency in JavaScript/TypeScript and one framework (React, Vue, Next.js, or Angular).",
      "Experience with backend development using Node.js, Express, or similar frameworks.",
      "Familiarity with relational and/or NoSQL databases (PostgreSQL, MongoDB, Firebase, etc.).",
      "Experience building REST APIs or GraphQL APIs.",
      "Good understanding of cloud services (AWS, GCP, Firebase, or Supabase).",
      "Experience with Git, CI/CD, and version control best practices.",
      "Ability to work independently and in a fast-moving startup.",
    ],
    niceToHave: [
      "Experience with EdTech platforms or gamified learning systems.",
      "Mobile app development (Flutter, React Native).",
      "AI integration experience (LLMs, AI tutoring tools, automations).",
      "Experience with deployment and DevOps (Docker, Kubernetes).",
    ],
    offer: [
      "Build a product that will shape the future of learning.",
      "High ownership + freedom to innovate.",
      "Work with a young, ambitious, mission-driven team.",
      "Competitive salary + performance and equity options.",
      "Clear growth path into senior engineering and leadership roles.",
    ],
    applicationLink: "https://docs.google.com/document/d/1CMo87ljBhARK_Dcq7Z1VDo2P9feSuOyh4SaGbSptdPM/edit?usp=drivesdk",
  },
  {
    id: 4,
    title: "Graphics Designer — Apprelab (EdTech)",
    type: "Full-time",
    location: "Remote/Hybrid",
    shortDescription: "Create stunning visuals for product, marketing, social media, and campaigns.",
    description: `Apprelab is an EdTech startup redefining digital learning across Africa. We're building a world-class team to create engaging learning experiences and powerful brand visuals.
The Graphics Designer will create high-quality visual assets for product, marketing, social media, campaigns, and brand identity. Work closely with the content, design, motion, and marketing teams to bring Apprelab's brand to life through creative and consistent visual storytelling.`,
    responsibilities: [
      "Design social media graphics, carousels, banners, posters, and marketing creatives.",
      "Produce visuals for campaigns, product launches, ads, and learning content.",
      "Create branded templates for the marketing and content teams.",
      "Support the product team with in-app visuals, icons, illustrations, and UI elements.",
      "Produce design assets that enhance user experience and engagement.",
      "Maintain and elevate Apprelab's brand identity across all materials.",
      "Help shape the visual language for the brand across platforms.",
      "Work closely with the Motion Designer to ensure smooth brand consistency across static and animated content.",
      "Collaborate with content creators, social media managers, and marketing lead to conceptualize designs.",
      "Translate briefs and ideas into polished designs that resonate with learners and partners.",
      "Deliver fast and iterate based on feedback.",
    ],
    requirements: [
      "1–3+ years experience in graphic design (startup or EdTech experience is a plus).",
      "Strong proficiency in Canva, Adobe Photoshop, Illustrator (Figma is a bonus).",
      "Strong portfolio showcasing creative, modern, and clean design style.",
      "Ability to design for both product UI and marketing/social contexts.",
      "Strong sense of typography, color theory, layout, and composition.",
      "Ability to work under pressure and meet deadlines.",
      "Strong aesthetics and attention to detail.",
    ],
    niceToHave: [
      "Illustration skills.",
      "Experience with branding systems.",
      "Experience working in a fast-paced startup environment.",
      "Ability to collaborate with motion designers and marketing teams.",
    ],
    offer: [
      "Be part of building Africa's next big EdTech brand.",
      "A creative, collaborative, fast-paced environment.",
      "Opportunities for career growth and leadership.",
      "Competitive salary + performance benefits.",
      "Work on meaningful learning-focused design projects.",
    ],
    applicationLink: "https://docs.google.com/document/d/12G_nI-Tf-c2fc1QpIdN9dwkyhgp8gv2AgVRTQnbCMJ0/edit?usp=drivesdk",
  },
  {
    id: 5,
    title: "HR & Operations Intern — Apprelab (EdTech)",
    type: "Full-time",
    location: "Remote/Hybrid",
    shortDescription: "Manage HR and operations, build processes, and support the growing team.",
    description: `Apprelab is an innovative EdTech startup shaping the future of digital learning in Africa. With rapid growth underway, we are building a team of talented, mission-driven individuals.
The HR & Operations Manager will oversee all core people functions, recruitment, onboarding, performance management, internal culture, and operational workflows within Apprelab. This role is perfect for someone who loves creating structure, improving processes, managing teams, and supporting the organisation as it scales.`,
    responsibilities: [
      "Lead end-to-end recruitment: sourcing, screening, interviewing, shortlisting, and onboarding.",
      "Develop HR policies, employee handbooks, and standard operating procedures.",
      "Manage payroll, employee records, and staff documentation.",
      "Build and maintain a positive company culture aligned with Apprelab's mission and values.",
      "Handle conflict resolution, employee welfare, and team feedback systems.",
      "Coordinate training and development programs for staff.",
      "Set up and manage performance review cycles, KPIs, and appraisal processes.",
      "Develop and optimize internal workflows, processes, and systems to improve efficiency.",
      "Oversee day-to-day operations to ensure the team is running smoothly.",
      "Coordinate with product, marketing, design, and content teams to ensure operational alignment.",
      "Ensure smooth communication and collaboration across departments.",
      "Manage administrative activities, documentation, scheduling, and internal communication.",
      "Support planning and execution of company events, product launches, and operational tasks.",
      "Work closely with founders to implement HR and operational strategies that support company growth.",
      "Help scale the organization by designing systems for hiring, team management, and long-term operations.",
      "Participate in leadership meetings and contribute to strategic planning.",
      "Ensure compliance with regulatory requirements and HR best practices.",
    ],
    requirements: [
      "2–5 years experience in HR, operations, or people management (startup experience is a big advantage).",
      "Strong understanding of HR processes, recruitment, culture development, and performance management.",
      "Excellent communication, organization, and leadership skills.",
      "Ability to build structure in a fast-moving startup environment.",
      "Strong problem-solving abilities and attention to detail.",
      "Ability to use HR tools, project management tools, and documentation platforms (Notion, Trello, Asana, etc.).",
    ],
    niceToHave: [
      "Experience working in tech, EdTech, or SaaS.",
      "Experience setting up HR from scratch in a startup environment.",
      "Certification in HR or People Operations (not mandatory).",
    ],
    offer: [
      "Join a fast-growing EdTech revolutionizing learning in Africa.",
      "Key leadership role with high ownership and influence.",
      "Competitive salary + benefits.",
      "Growth opportunities as the company expands.",
      "Work with a young, dynamic, mission-driven team.",
    ],
    applicationLink: "https://docs.google.com/document/d/1gTulQZPxtX3n3Ew5L7v6T39arD2KrAeR3PPP4gIeRkk/edit?usp=drivesdk",
  },
  {
    id: 6,
    title: "Marketing Lead — Apprelab (EdTech)",
    type: "Full-time",
    location: "Remote/Hybrid",
    shortDescription: "Lead Apprelab's marketing strategy, user acquisition, and brand growth.",
    description: `Apprelab is an EdTech startup building the future of learning in Africa. We help learners grow through practical, gamified, and community-driven digital experiences. With our recent launch, we're assembling a world-class team to scale fast — and we need a Marketing Lead who can turn Apprelab into a household name.
The Marketing Lead will be responsible for driving Apprelab's marketing strategy, brand positioning, user acquisition, and product growth. You'll oversee all marketing operations — from campaigns to storytelling, funnels, content, brand partnerships, and execution.`,
    responsibilities: [
      "Develop and execute Apprelab's global marketing strategy.",
      "Build and lead a high-performing marketing team (content, social, design, growth).",
      "Own brand positioning, messaging, and communication across all platforms.",
      "Collaborate with product team to align marketing with product launches and updates.",
      "Develop data-driven acquisition strategies to increase signups, retention, and referrals.",
      "Launch and optimise funnels, campaigns, and growth loops.",
      "Run experiments (A/B tests, CTA tests, pricing tests) to improve acquisition metrics.",
      "Build strategies for organic and paid growth across social, SEO, communities, and partnerships.",
      "Oversee content creation across all platforms: social media, blog, email, in-app, video, PR, and YouTube.",
      "Drive consistent storytelling that differentiates Apprelab in the EdTech space.",
      "Create and maintain brand guidelines, tone, and visual identity with the design team.",
      "Plan and run monthly and quarterly marketing campaigns.",
      "Build strong communities around learning, technology, and growth.",
      "Activate influencers, creators, micro-communities, and ambassadors.",
      "Collaborate with schools, EdTech ecosystems, and startup communities to boost visibility.",
      "Track and analyse key marketing metrics: CAC, LTV, activation rates, conversion, retention, DAU/MAU, etc.",
      "Produce weekly and monthly dashboards to guide decision-making.",
      "Report directly to the COO and CEO on strategy performance and improvements.",
    ],
    requirements: [
      "3+ years experience in marketing, preferably in tech, EdTech, SaaS, or a startup environment.",
      "Strong understanding of growth marketing, digital ads, campaigns, and user psychology.",
      "Proven experience leading teams or managing cross-functional projects.",
      "Strong storytelling, content strategy, and brand development skills.",
      "Familiarity with analytics tools (Google Analytics, Mixpanel, HubSpot, Meta/TikTok ads).",
      "Creative thinker with the ability to execute quickly and iterate.",
      "Ability to communicate complex ideas simply and persuasively.",
    ],
    niceToHave: [
      "Experience in EdTech, online learning, or gamified products.",
      "Background in product marketing or GTM strategy.",
      "Experience hosting webinars, workshops, or community events.",
    ],
    offer: [
      "A leadership position with massive impact on the company's growth trajectory.",
      "Freedom to build and shape the entire marketing ecosystem.",
      "Competitive salary + bonuses + career growth.",
      "Work with a driven, young, and innovative team building the future of education.",
      "Opportunity to create a portfolio of large-scale, meaningful work.",
    ],
    applicationLink: "https://docs.google.com/document/d/1CnNhF_h8QG9DeQqGud5eGCnGMU0y7SID5-in1sAGpkg/edit?usp=drivesdk",
  },
  {
    id: 7,
    title: "Growth & Partnerships Lead — Apprelab (EdTech)",
    type: "Full-time",
    location: "Remote/Hybrid",
    shortDescription: "Drive growth, secure partnerships, and expand Apprelab across Africa.",
    description: `We're looking for a strategic and fearless Growth & Partnerships Lead to help Apprelab expand rapidly across Africa. This person will drive growth, secure partnerships, unlock funding opportunities, and create collaborations required for market dominance.
You will build relationships with schools, EdTech stakeholders, agencies, communities, creators, SMEs, and government bodies.`,
    responsibilities: [
      "Develop and execute strategies to grow user acquisition, retention, and engagement.",
      "Identify new markets, user segments, and distribution channels.",
      "Lead growth experiments to boost onboarding, referrals, and virality.",
      "Work with marketing, product, and data teams to achieve growth KPIs.",
      "Identify, pitch, and secure partnerships with schools, training centers, SMEs, NGOs, tech communities, and creator networks.",
      "Build relationships with brands and organizations that align with Apprelab's mission.",
      "Manage partnerships end-to-end, from outreach to negotiation to onboarding.",
      "Explore collaboration opportunities with companies seeking digital learning solutions.",
      "Research and identify grant programs, accelerators, competitions, and funding opportunities.",
      "Prepare partnership decks, growth proposals, pitch documents, and investment materials.",
      "Represent Apprelab in demos, pitches, and strategic events.",
      "Work directly with founders on expansion strategies.",
    ],
    requirements: [
      "Proven experience in partnerships, growth marketing, business development, or fundraising.",
      "Strong communication, pitching, and negotiation skills.",
      "Understanding of EdTech, startups, or SaaS markets.",
      "Ability to build relationships and close deals.",
      "Entrepreneurial mindset — comfortable working under uncertainty and moving fast.",
      "Familiarity with grant writing, fundraising, and proposal development (bonus).",
    ],
    niceToHave: [
      "Experience in startup growth and international expansion.",
      "Connections with EdTech stakeholders, schools, or SMEs.",
      "Experience with venture capital or grant applications.",
    ],
    offer: [
      "A strategic leadership role in a fast-growing EdTech.",
      "High ownership + direct impact on Apprelab's growth and funding.",
      "Competitive salary + performance or commission bonuses.",
      "Opportunity to build and lead the partnerships arm of the company.",
    ],
    applicationLink: "https://docs.google.com/document/d/1Hy1ymMBvyqILjkDDEd4ZIfwGTmIUhDRXblPRYvHtUYc/edit?usp=drivesdk",
  },
  {
    id: 8,
    title: "Motion Designer — Apprelab (EdTech)",
    type: "Full-time",
    location: "Remote/Hybrid",
    shortDescription: "Bring Apprelab's brand and educational content to life with motion graphics.",
    description: `Apprelab is looking for a highly creative Motion Designer to bring our learning content, brand stories, and product experiences to life through stunning motion graphics. You will be the visual storyteller behind our brand — crafting videos that make learning fun, dynamic, and impossible to ignore.`,
    responsibilities: [
      "Create high-quality motion graphics, animations, explainer videos, product demos, and social media visuals.",
      "Collaborate with the content, design, and marketing teams to create engaging educational animations.",
      "Work with product team to develop UI/UX motion assets for in-app experiences.",
      "Translate scripts, concepts, and raw ideas into polished animated content.",
      "Develop visual systems for Apprelab's storytelling style (transitions, character movement, effects, brand animation guidelines).",
      "Maintain brand consistency across all video assets.",
      "Stay updated with trends in animation, EdTech visuals, and creative storytelling.",
    ],
    requirements: [
      "Strong portfolio of motion design work.",
      "Proficiency in After Effects, Premiere Pro, Blender/Cinema4D (bonus), or similar tools.",
      "Ability to animate characters, text, interfaces, and educational scenes.",
      "Good sound design sense (bonus).",
      "Creative, detail-oriented, and able to work in a fast-paced startup environment.",
    ],
    niceToHave: [
      "Experience in EdTech content creation or educational animation.",
      "Knowledge of 3D animation or interactive media.",
      "Experience collaborating with marketing or design teams in a startup.",
    ],
    offer: [
      "Work on meaningful educational content at scale.",
      "Creative freedom + a collaborative team.",
      "Competitive salary and growth opportunities.",
    ],
    applicationLink: "https://docs.google.com/document/d/1yJE_Yy-KzWuFR8Mr5ilv5zbjX_oxj6TeLN9NEACAU38/edit?usp=drivesdk",
  },
  {
    id: 9,
    title: "Social Media Manager — Apprelab (EdTech)",
    type: "Full-time",
    location: "Remote/Hybrid",
    shortDescription: "Own Apprelab's social presence and drive growth across all platforms.",
    description: `Apprelab is an EdTech startup on a mission to build Africa's most effective digital learning ecosystem. We've just launched and are scaling fast. We create learning experiences that feel like play, powered by smart technology, community, and innovation. We integrate learning, working and earning. 
We're expanding our team and looking for a creative, data-driven Social Media Manager to help us dominate the EdTech space.`,
    responsibilities: [
      "Develop and execute monthly social media strategies aligned with brand and product goals.",
      "Create high-quality content (videos, reels, carousels, short-form educational content, graphics).",
      "Craft compelling copy for posts, campaigns, and ads.",
      "Translate product features into user-friendly, fun, and engaging content.",
      "Manage all social channels: TikTok, Instagram, LinkedIn, X, YouTube, Facebook.",
      "Ensure consistent brand voice across platforms.",
      "Keep up with trends, audio, memes, learning hacks, and EdTech conversations.",
      "Build a strong online community around learning, creativity, and growth.",
      "Respond to comments, DMs, and user feedback.",
      "Work with users, creators, and influencers to activate community challenges.",
      "Track growth metrics: reach, engagement, retention, conversions, and user activation.",
      "Run experiments (A/B tests, content variations, platform tests).",
      "Report insights weekly and monthly, including what's working and what's not.",
      "Work closely with design, content, product, and marketing teams.",
      "Sync with product launch timelines, feature updates, and campaigns.",
      "Support paid media efforts with social-led ideas and creatives.",
    ],
    requirements: [
      "Proven experience managing brand or creator social accounts.",
      "Strong content creation skills (short-form videos, copywriting, visual storytelling).",
      "Ability to make educational content fun, simple, and shareable.",
      "Familiarity with social media analytics tools.",
      "Understanding of EdTech, gamification, or online learning (bonus).",
      "Strong communication and community management skills.",
      "Highly creative with the ability to move fast and execute consistently.",
    ],
    niceToHave: [
      "Degree in Marketing, Communications, English, Media, or equivalent experience.",
      "Experience with Canva, CapCut, Adobe tools, or similar.",
      "1–3 years relevant experience in social media or digital marketing.",
    ],
    offer: [
      "Opportunity to build something meaningful from the ground up.",
      "A creative, flexible, fast-paced work environment.",
      "Growth opportunities within a rapidly scaling EdTech startup.",
      "Competitive salary + performance incentives.",
      "Work with a young, innovative, mission-driven team.",
    ],
    applicationLink: "https://docs.google.com/document/d/1JeJYmJdf2fs1dSZJUHiiri_szb6qEXKsdNuFy3LQHB4/edit?usp=drivesdk",
  }
];